spring:
  application:
    name: "http-service1"
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317/v1/traces


server:
  port: 8086

logging:
  path: /Users/puneet.dewan/Code/zendesk/distributed-tracing-demo/otel-http/pd.log
  level:
    org.springframework.cloud.sleuth: DEBUG
    io.opentelemetry: DEBUG